version: 1.0.{build}

environment:
  matrix:
    - compiler: mingw32
    - compiler: mingw-w64

install:
# Rename sh.exe as sh.exe in PATH interferes with MinGW
- rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
- if [%compiler%]==[mingw32] set PATH=C:\MinGW\bin;%PATH%
- if [%compiler%]==[mingw-w64] set PATH=C:\MinGW\bin;%PATH%

before_build:
- mkdir build
- cd build
- if "%compiler%"=="mingw32" (set GENERATOR="MinGW Makefiles")
- if "%compiler%"=="mingw-w64" (set GENERATOR="MinGW Makefiles")
- cmake .. -G %GENERATOR% -DCOLLECT_STATIC_VAR_DATA=ON

build_script:
- if "%compiler%"=="mingw32" mingw32-make all
- if "%compiler%"=="mingw-w64" mingw32-make all

test_script:
- cd c:\projects\MemPlumber\build
- ctest --verbose